apiVersion: apps/v1
kind: Deployment
metadata:
  name: discount-system-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discount-system
  template:
    metadata:
      labels:
        app: discount-system
    spec:
      containers:
      - name: discount-container
        image: discount-app:v1
        imagePullPolicy: Never  # This tells K8s to use the image we just built locally
        ports:
        - containerPort: 8080